[package]
name = "axum-askama"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.9.0", features = ["full"] }
axum = { version = "0.7.9", features = ["macros"] }
askama = "0.12.1"
